### ISSUE TITLE
TreeView Item template causing crash

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#250]
After setting the model to a TreeView using templates... nothing updates...

Then if I maximize the window forcing an update...

It crashes with  NullReferenceException

```
   at Perspex.Markup.Xaml.Templates.TreeDataTemplate.Match(Object data)
   at Perspex.Controls.Templates.DataTemplateExtensions.FindDataTemplate(IControl control, Object data)
   at Perspex.Controls.Generators.TreeItemContainerGenerator`1.GetTreeDataTemplate(Object item)
   at Perspex.Controls.Generators.TreeItemContainerGenerator`1.CreateContainer(Object item)
   at Perspex.Controls.Generators.TreeItemContainerGenerator`1.CreateContainers(Int32 startingIndex, IEnumerable items, IMemberSelector selector)
   at Perspex.Controls.Presenters.ItemsPresenter.CreateItemsAndListenForChanges(IEnumerable items)
   at Perspex.Controls.Presenters.ItemsPresenter.CreatePanel()
   at Perspex.Controls.Presenters.ItemsPresenter.ApplyTemplate()
   at Perspex.Controls.Primitives.TemplatedControl.SetTemplatedParentAndApplyChildTemplates(IControl control)
   at Perspex.Controls.Primitives.TemplatedControl.SetTemplatedParentAndApplyChildTemplates(IControl control)
   at Perspex.Controls.Primitives.TemplatedControl.ApplyTemplate()
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Presenters.ItemsPresenter.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Presenters.ScrollContentPresenter.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Controls.Presenters.ContentPresenter.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Grid.MeasureOverride(Size constraint)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Perspex.Controls.ScrollViewer.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Border.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Grid.MeasureOverride(Size constraint)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Border.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Controls.Presenters.ContentPresenter.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Border.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Grid.MeasureOverride(Size constraint)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Grid.MeasureOverride(Size constraint)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Controls.Presenters.ContentPresenter.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Decorator.MeasureOverride(Size availableSize)
   at Perspex.Controls.Primitives.AdornerDecorator.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Controls.Border.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Perspex.Controls.Window.MeasureOverride(Size availableSize)
   at Perspex.Layout.Layoutable.MeasureCore(Size availableSize)
   at Perspex.Layout.Layoutable.Measure(Size availableSize, Boolean force)
   at Perspex.Layout.LayoutManager.ExecuteMeasure()
   at Perspex.Layout.LayoutManager.ExecuteLayoutPass()
   at Perspex.Controls.TopLevel.HandleResized(Size clientSize)
   at Perspex.Controls.Window.HandleResized(Size clientSize)
   at Perspex.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Perspex.Win32.Interop.UnmanagedMethods.DefWindowProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Perspex.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
```

Contact me for help to repro

**Comment by grokys** [comment]
Could you try this again with the latest nightly, and if that doesn't fix it, explain to me how i can repro?

**Comment by danwalmsley** [comment]
Ok a lot better now... however I can trigger exception by doing something similar...

"An item with the same key has already been added."

**Comment by grokys** [comment]
This seems to be happening because something is modifying the collection that the TreeView is bound to whilst the TreeView is generating its items. Any idea what might be causing this?

I don't think it's something we want to harden right now as `ItemContainerGenerators` will need to be re-done for virtualization anyway.

**Comment by danwalmsley** [comment]
I've found where it is being modified... for some reason Perspex is setting my Title property on the model.. which triggers a rename in the model... modifying the viewmodel...

Perhaps this is a problem with Perspex... will just test on WPF version to see if its happening there,

**Comment by danwalmsley** [comment]
Ok this issue can be closed as fixed... May need to open another issue regarding setting the text value will need to investigate further first.
