### ISSUE TITLE
Unable to Bind to TextBox.CaretIndex property

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#270]
This was fixed... but something else has broken it again...

Casting issue.

**Comment by danwalmsley** [comment]
@grokys please re-open the issue persists in latest nightly build.

**Comment by danwalmsley** [comment]
Specified cast is not valid.

   at Perspex.PerspexProperty`1.<>c__DisplayClass17_0.<Cast>b__0(PerspexObject o, Object v)
   at Perspex.PerspexObject.<>c__DisplayClass50_0.<CreatePriorityValue>b__0(Object v)
   at Perspex.PriorityValue.UpdateValue(Object value, Int32 priority)
   at Perspex.PriorityValue.ValueChanged(PriorityLevel level)
   at Perspex.PriorityLevel.ActivateFirstBinding()
   at Perspex.PriorityLevel.Changed(PriorityBindingEntry entry)
   at Perspex.PriorityBindingEntry.<>c__DisplayClass17_0.<Start>b__0(Object value)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   at System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at Perspex.Markup.Binding.ExpressionNode.Subscribe(IObserver`1 observer)
   at Perspex.Markup.Binding.ExpressionObserver.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.ObservableImpl.Select`2.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.Run(IScheduler _, State x)
   at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.Reactive.Producer`1.Subscribe(IObserver`1 observer)
   at Perspex.Markup.Binding.ExpressionSubject.Subscribe(IObserver`1 observer)
   at System.ObservableExtensions.Subscribe[T](IObservable`1 source, Action`1 onNext, Action onCompleted)
   at Perspex.PriorityBindingEntry.Start(IObservable`1 binding, Action`1 changed, Action`1 completed)
   at Perspex.PriorityLevel.Add(IObservable`1 binding)
   at Perspex.PerspexObject.Bind(PerspexProperty property, IObservable`1 source, BindingPriority priority)
   at Perspex.PerspexObject.BindTwoWay(PerspexProperty property, ISubject`1 source, BindingPriority priority)
   at Perspex.Markup.Xaml.Binding.XamlBinding.Bind(IObservablePropertyBag target, PerspexProperty property, ISubject`1 subject)
   at Perspex.Markup.Xaml.Binding.XamlBinding.Bind(IObservablePropertyBag instance, PerspexProperty property)
   at Perspex.Markup.Xaml.Context.PerspexXamlMemberValuePlugin.HandleXamlBindingDefinition(Object instance, XamlBindingDefinition def)
   at Perspex.Markup.Xaml.Context.PerspexXamlMemberValuePlugin.SetValue(Object instance, Object value)
   at OmniXaml.ObjectAssembler.StateCommuter.AssignChildToParentProperty()
   at OmniXaml.ObjectAssembler.StateCommuter.AssociateCurrentInstanceToParent()
   at OmniXaml.ObjectAssembler.Commands.EndObjectCommand.Execute()
   at OmniXaml.ObjectAssembler.ObjectAssembler.Process(XamlInstruction instruction)
   at OmniXaml.TemplateHostingObjectAssembler.Process(XamlInstruction instruction)
   at Perspex.Markup.Xaml.Context.PerspexObjectAssembler.Process(XamlInstruction node)
   at OmniXaml.XamlXmlParser.Parse(IEnumerable`1 xamlNodes)
   at OmniXaml.XamlXmlParser.Parse(Stream stream)
   at Perspex.Markup.Xaml.PerspexXamlLoader.Load(Type type, Object rootInstance)
   at Perspex.Markup.Xaml.PerspexXamlLoader.Load(Object obj)
   at AvalonStudio.Controls.Editor.InitializeComponent() in D:\Development\Repos\AvalonStudio\AvalonStudio\AvalonStudio\Controls\Editor.paml.cs:line 15
   at AvalonStudio.Controls.Editor..ctor() in D:\Development\Repos\AvalonStudio\AvalonStudio\AvalonStudio\Controls\Editor.paml.cs:line 10

**Comment by grokys** [comment]
Now fixed I believe.
