### ISSUE TITLE
Could not load type 'SharpDX.Matrix3x2' from assembly 'SharpDX, Version=3.0.1.0,

### ISSUE THREAD

**Issue by mafshin** [Perspex/Perspex#415]
> An unhandled exception of type 'System.TypeLoadException' occurred in Perspex.SceneGraph.dll

Additional information: Could not load type 'SharpDX.Matrix3x2' from assembly 'SharpDX, Version=3.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1'.

**StackTrace:**

```
   at Perspex.Direct2D1.Media.DrawingContext.set_Transform(Matrix value)
   at Perspex.Rendering.RendererMixin.Render(DrawingContext context, IVisual visual)
   at Perspex.Rendering.RendererMixin.Render(IRenderTarget renderTarget, IVisual visual)
   at Perspex.Controls.Platform.DefaultTopLevelRenderer.<>c__DisplayClass0_0.<Attach>b__2(Rect rect)
   at Perspex.Controls.Platform.PlatformManager.WindowDecorator.OnPaint(Rect rc)
   at Perspex.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
```

**Packages.config**

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Perspex" version="0.2.0-alpha3" targetFramework="net461" />
  <package id="Perspex.Desktop" version="0.2.0-alpha3" targetFramework="net461" />
  <package id="Rx-Core" version="2.2.5" targetFramework="net461" />
  <package id="Rx-Interfaces" version="2.2.5" targetFramework="net461" />
  <package id="Rx-Linq" version="2.2.5" targetFramework="net461" />
  <package id="Rx-Main" version="2.2.5" targetFramework="net461" />
  <package id="Rx-PlatformServices" version="2.2.5" targetFramework="net461" />
  <package id="Rx-XAML" version="2.2.5" targetFramework="net461" />
  <package id="Serilog" version="2.0.0-beta-479" targetFramework="net461" />
  <package id="SharpDX" version="3.0.1" targetFramework="net461" />
  <package id="SharpDX.Direct2D1" version="3.0.1" targetFramework="net461" />
  <package id="SharpDX.DXGI" version="3.0.1" targetFramework="net461" />
  <package id="Splat" version="1.6.2" targetFramework="net461" />
  <package id="Sprache" version="2.0.0.50" targetFramework="net461" />
</packages>
```

**Comment by wieslawsoltes** [comment]
Try upgrading to Perspex nightly builds : https://github.com/Perspex/Perspex/wiki/Using-nightly-build-feed

**Comment by mafshin** [comment]
Using nightly build and the issue is resolved.
